version: '3.9'

services:
  JSProj:
    image: transloadit/companion
    create:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /mnt/JSProj-server-data:/mnt/JSProj-server-data
    ports:
      - '3020:3020'
    env_file:
      - .env
